# Calculations for Results Tables

The code below will perform the calculations to make the data tables presented in the class handout.

First, we will calculate values of $k_H/k_a$ and values for $pK_a$ from the `results.csv` file.  We will write the edited results to a file called `results2.csv` and use that text in making the data table in the handout.

Then we will calculate the same values from the author's data in table 1 of the paper.  the data has been entered into a file named `Table1data.csv`.  Take note that a typographical error was identified in the table and corrected (molecule **1f** has a $k_{AR}$ for $pH = 1.0$ reported as $7.83\times 10^{-4}~s^{-1}$ and the correct value was judged to be $7.83\times 10^{-5}~s^{-1}$)

Table 1 is found in "On the Rearrangement in Dioxane/Water of (*Z*)-Arylhydrazones of 5-Amino-3-benzoyl-1,2,4-oxadiazole into (2-Aryl-5-phenyl-2*H*-1,2,3-triazol-4-yl)ureas: Substituent Effects on the Different Reaction Pathways." F. D'Anna, V. Frenna, G. Macaluso, S. Marullo, S. Morganti, V. Pace, D. Spinelli, R. Spisani, C. Tavani, *J. Org. Chem.*, **2006**, *71*, 5616-5624. https://doi.org/10.1021/jo0605849

In [14]:
# uncomment and run commands below when using Google Colab
# 
#!pip install uncertainties
#!pip install lmfit
#!mkdir images
#!mkdir data

In [15]:
##############################################################
### Set up libraries and global variables
##############################################################

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import scipy.constants as constants  # a collection of scientific constants
from scipy.optimize import curve_fit


github = False    # set to True if reading data from GitHub  

if github == True:
    github_location = "https://raw.githubusercontent.com/blinkletter/4410PythonNotebooks/main/Class_23/data/"
    github_location_styles = "https://raw.githubusercontent.com/blinkletter/LFER-QSAR/main/styles/"
    github_location_LFER_tables = "https://raw.githubusercontent.com/blinkletter/4410PythonNotebooks/main/Class_23/data/"
else:  
    github_location = "data/"
    github_location_styles = "../../styles/"
    github_location_LFER_tables = "~/github/LFER-QSAR/data/"

datafile_name = "results.csv"

##############################################################
### Read data for thermodynamic parameters
##############################################################

df = pd.read_csv(github_location + datafile_name, 
             delimiter = ",", 
             skipinitialspace=True, 
             index_col="Substituent", 
             comment = "#") 
display(df)

df2 = df[["molecule","kOH","kH2O","kHKa"]].copy()
df2["pKa"]=-np.log10(df["Ka"])

if True:   # add text for LaTeX
    df2["molecule"]="\textbf{"+df2["molecule"]+"}"    # add LaTeX code for use in table in LaTeX document
    df2.index = "\ce{"+df2.index+"}"
    df2["kH2O x 10^6"] = df2["kH2O"] * 1E6
    df2["kH/Ka x 10^3"]=df2["kHKa"] * 1E3

#print(df["kH2O"])
df3 = df2[["molecule","kOH","kH2O x 10^6","kH/Ka x 10^3","pKa"]].copy()
df3.to_csv("data/results2.csv")
df3

<>:42: SyntaxWarning: invalid escape sequence '\c'
<>:42: SyntaxWarning: invalid escape sequence '\c'
/var/folders/_0/pb9y62rd59n_3vs7rbl1bndm0000gn/T/ipykernel_24785/1800006264.py:42: SyntaxWarning: invalid escape sequence '\c'
  df2.index = "\ce{"+df2.index+"}"

,sigma,s_plus,s_minus,sigma_I,sigma_n,sigma_star,F,R,R+,R-,...,Ka,kOH,kH2O,kH,kHKa,Ka_sd,kOH_sd,kH2O_sd,kH_sd,kHKa_sd
Substituent,,,,,,,,,,,,,,,,,,,,,
p-OCH3,-0.27,-0.78,-0.27,0.29,-0.09,0.52,0.29,-0.56,-1.07,-0.55,...,0.4682,2.177,1.245000e-05,0.002322,0.004959,0.07780,0.06324,4.121000e-07,0.000304,0.000260
p-CH3,-0.17,-0.31,-0.17,-0.01,-0.10,-0.10,0.01,-0.18,-0.32,-0.18,...,0.4525,1.564,1.197000e-05,0.001956,0.004324,0.05586,0.03957,3.419000e-07,0.000181,0.000194
m-CH3,-0.07,-0.07,-0.07,NaN,NaN,NaN,NaN,0.00,0.00,0.00,...,0.5912,1.368,8.776000e-06,0.002061,0.003486,0.09015,0.03981,3.292000e-07,0.000252,0.000153
H,0.00,0.00,0.00,NaN,NaN,0.00,0.00,0.00,0.00,0.00,...,0.5597,1.311,6.620000e-06,0.001902,0.003399,0.10010,0.04700,3.460000e-07,0.000239,0.000222
p-Cl,0.23,0.11,0.23,0.47,0.29,1.05,0.42,-0.19,-0.31,-0.23,...,0.8075,6.306,3.822000e-06,0.000959,0.001188,0.23160,0.28140,2.267000e-07,0.000228,0.000083
p-Br,0.23,0.15,0.23,0.47,0.30,1.00,0.45,-0.22,-0.30,-0.20,...,0.9740,7.726,3.287000e-06,0.000957,0.000983,0.33660,0.35250,2.021000e-07,0.000276,0.000078
m-Cl,0.37,0.37,0.37,NaN,NaN,NaN,NaN,0.00,0.00,0.00,...,1.0240,10.730,2.539000e-06,0.000775,0.000757,0.29720,0.40180,1.372000e-07,0.000187,0.000050
m-Br,0.39,0.39,0.39,NaN,NaN,NaN,NaN,0.00,0.00,0.00,...,0.9591,11.640,2.417000e-06,0.000687,0.000716,0.26060,0.43760,1.246000e-07,0.000152,0.000049
p-CN,0.66,0.66,1.00,0.70,0.66,1.30,0.51,0.15,0.15,0.49,...,1.1010,143.900,8.246000e-07,0.000221,0.000201,0.36860,5.77900,6.531000e-08,0.000062,0.000015
m-NO2,0.71,0.71,0.71,NaN,NaN,NaN,NaN,0.00,0.00,0.00,...,1.3570,75.300,9.372000e-07,0.000298,0.000219,0.62580,3.55800,7.173000e-08,0.000120,0.000018
p-NO2,0.78,0.78,1.27,0.67,0.78,NaN,0.65,0.13,0.14,0.62,...,2.0000,635.200,4.714000e-07,0.000227,0.000114,3.76400,35.48000,5.354000e-08,0.000408,0.000013

                molecule      kOH  kH2O x 10^6  kH/Ka x 10^3       pKa
Substituent
\ce{p-OCH3}  \textbf{1c}    2.177      12.4500        4.9590  0.329569
\ce{p-CH3}   \textbf{1e}    1.564      11.9700        4.3240  0.344381
\ce{m-CH3}   \textbf{1d}    1.368       8.7760        3.4860  0.228266
\ce{H}       \textbf{1b}    1.311       6.6200        3.3990  0.252045
\ce{p-Cl}    \textbf{1g}    6.306       3.8220        1.1880  0.092857
\ce{p-Br}    \textbf{1i}    7.726       3.2870        0.9828  0.011441
\ce{m-Cl}    \textbf{1f}   10.730       2.5390        0.7567 -0.010300
\ce{m-Br}    \textbf{1h}   11.640       2.4170        0.7164  0.018136
\ce{p-CN}    \textbf{1j}  143.900       0.8246        0.2012 -0.041787
\ce{m-NO2}   \textbf{1k}   75.300       0.9372        0.2194 -0.132580
\ce{p-NO2}   \textbf{1l}  635.200       0.4714        0.1136 -0.301030

## Table 1 data

And here is the code for making the table 1 data for the handout. We will convert the values reported in table 1 to the format used in my own analysis.

in table 1 we make the following calculations.

$k_{AR}, pH=1.0$ is the first order rate constant when [H] = 0.1M.  Using the authors values for kH and Ka in table 1 we could calculate that...

$k_{AR} = k_H \frac{[H]}{[H]+K_a}$

I presume that the authors obtained $K_a$ and $k_H$ values by fitting the value of $k_{AR}$ vs $pH$ in the range where the acidic reaction dominates the rate. When I use the values of $K_a$ and $k_H$ to calculate the rates at $pH = 1.0$, I get values that are 1.3 to 3-fold greater than the authors' measured $k_{AR}$ values.

From the authors table 1 the following values are calculated...

$k_{OH}$ is $k_{AR_{pH=11.5}} \times [OH]_{pH=11.5}$ or $k_{AR_{pH=11.5}}\cdot 10^{(14-11.5)}$

$k_{H2O}$ is the $k_{AR_{pH=3.8}}$ value

$\frac{k_H}{K_a}$ is the calculated using the values of $k_H$ and $K_a$ reported in table 1.

In [16]:
##############################################################
### Read data for thermodynamic parameters
##############################################################

datafile_name = "Table1data.csv"



df = pd.read_csv(github_location + datafile_name, 
             delimiter = ",", 
             skipinitialspace=True, 
             index_col="Substituent", 
             comment = "#") 
display(df)

df2 = df[["Molecule","K"]].copy()
df2["kOH"]=df["kAR_pS_11.5"]/(10**(-14)/10**(-11.5))
df2["kH2O x 10^6"]=df["kAR_pS_3.80"]*1E6
df2["kH/Ka x 10^3"]=df["kH"]*1E3



df2.to_csv("data/table1results1.csv")
df2

            Molecule  kAR_pS_11.5   kAR_pS_3.80  kAR_pS_1.0        kH      K
Substituent
p-OCH3            1c      0.00395  1.240000e-05    0.000422  0.002130  1.400
p-CH3             1e      0.00467  1.190000e-05    0.000371  0.001880  1.340
m-CH3             1d      0.00641  9.180000e-06    0.000316  0.001770  1.230
H                 1b      0.00368  7.940000e-06    0.000286  0.001580  1.230
p-Br              1i      0.02000  3.440000e-06    0.000105  0.000652  1.060
p-Cl              1g      0.01610  3.990000e-06    0.000119  0.000726  1.080
m-Cl              1f      0.02690  2.710000e-06    0.000078  0.000533  0.976
m-Br              1h      0.03120  2.640000e-06    0.000075  0.000495  0.983
p-CN              1j      0.32100  9.500000e-07    0.000022  0.000155  0.880
m-NO2             1k      0.15800  9.950000e-07    0.000024  0.000180  0.868
p-NO2             1l      1.19000  6.100000e-07    0.000012       NaN    NaN

            Molecule      K         kOH  kH2O x 10^6  kH/Ka x 10^3
Substituent
p-OCH3            1c  1.400    1.249100       12.400         2.130
p-CH3             1e  1.340    1.476784       11.900         1.880
m-CH3             1d  1.230    2.027020        9.180         1.770
H                 1b  1.230    1.163718        7.940         1.580
p-Br              1i  1.060    6.324555        3.440         0.652
p-Cl              1g  1.080    5.091267        3.990         0.726
m-Cl              1f  0.976    8.506527        2.710         0.533
m-Br              1h  0.983    9.866306        2.640         0.495
p-CN              1j  0.880  101.509113        0.950         0.155
m-NO2             1k  0.868   49.963987        0.995         0.180
p-NO2             1l    NaN  376.311042        0.610           NaN